# Generated by Django 5.2.8 on 2026-05-07 20:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalCapstone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('mitra', models.CharField(max_length=255)),
                ('nim_ketua', models.CharField(max_length=20)),
                ('nim_anggota', models.JSONField(blank=True, default=list)),
                ('kategori', models.CharField(choices=[('EPD', 'EPD'), ('SM', 'SM')], max_length=3)),
                ('file', models.FileField(upload_to='proposal/')),
                ('waktu_pengajuan', models.DateTimeField(auto_now_add=True)),
                ('waktu_update', models.DateTimeField(auto_now=True)),
                ('waktu_peninjauan', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('BELUM_REVIEW', 'Belum Review'), ('SEDANG_REVIEW', 'Sedang Review'), ('DITERIMA', 'Diterima'), ('DITOLAK', 'Ditolak')], default='BELUM_REVIEW', max_length=20)),
                ('keterangan', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(blank=True, choices=[('MAHASISWA', 'Mahasiswa'), ('DOSENCP', 'Dosen CP'), ('DOSENPB', 'Dosen Pembimbing'), ('KAPRODI', 'Kaprodi')], max_length=20, null=True)),
                ('is_password_changed', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=20, unique=True)),
                ('bidang_keahlian', models.CharField(max_length=255)),
                ('status_aktif', models.BooleanField(default=True)),
                ('foto_profil', models.ImageField(blank=True, null=True, upload_to='foto_dosen/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DosenCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tugas', models.TextField()),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cp', to='capstone_system.dosen')),
            ],
        ),
        migrations.CreateModel(
            name='DosenPembimbing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batas_bimbingan', models.IntegerField(default=5)),
                ('jumlah_bimbingan_sekarang', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FULL', 'Full'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pembimbing', to='capstone_system.dosen')),
            ],
        ),
        migrations.CreateModel(
            name='JadwalKonsultasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('status', models.CharField(choices=[('tersedia', 'Tersedia'), ('dipesan', 'Dipesan')], default='tersedia', max_length=20)),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal', to='capstone_system.dosenpembimbing')),
            ],
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=20, unique=True)),
                ('kelas', models.CharField(max_length=5)),
                ('angkatan', models.CharField(max_length=10)),
                ('foto_profil', models.ImageField(blank=True, null=True, upload_to='foto_profil/')),
                ('dosen_pembimbing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mahasiswa_bimbingan', to='capstone_system.dosenpembimbing')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_proposal', models.CharField(max_length=255)),
                ('mitra', models.CharField(max_length=255)),
                ('sub_judul', models.CharField(max_length=255)),
                ('kategori', models.CharField(choices=[('EPD', 'EPD'), ('SM', 'SM')], max_length=3)),
                ('file_resume', models.FileField(upload_to='resume/')),
                ('waktu_pengajuan', models.DateTimeField(auto_now_add=True)),
                ('waktu_peninjauan', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('BELUM_REVIEW', 'Belum Review'), ('DISETUJUI', 'Disetujui'), ('DITOLAK', 'Ditolak'), ('REVISI', 'Revisi')], default='BELUM_REVIEW', max_length=20)),
                ('catatan_revisi', models.TextField(blank=True)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capstone_system.mahasiswa')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capstone_system.proposalcapstone')),
            ],
        ),
        migrations.CreateModel(
            name='PengajuanDospem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pengajuan', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DISETUJUI', 'Disetujui'), ('DITOLAK', 'Ditolak'), ('REVISI', 'Revisi')], default='PENDING', max_length=20)),
                ('sudah_direview', models.BooleanField(default=False)),
                ('waktu_direview', models.DateTimeField(blank=True, null=True)),
                ('catatan_dosen', models.TextField(blank=True)),
                ('surat_permohonan_dospem', models.FileField(upload_to='surat_permohonan/')),
                ('dosen_pembimbing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajuan', to='capstone_system.dosenpembimbing')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajuan_dospem', to='capstone_system.mahasiswa')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajuan_dospem', to='capstone_system.resume')),
            ],
        ),
    ]
