# Generated by Django 5.2.8 on 2026-05-11 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_tim', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Disetujui'), ('REJECTED', 'Ditolak')], default='PENDING', max_length=20)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='proposalcapstone',
            name='nim_anggota',
        ),
        migrations.RemoveField(
            model_name='proposalcapstone',
            name='nim_ketua',
        ),
        migrations.CreateModel(
            name='AnggotaTim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ketua', 'Ketua'), ('anggota', 'Anggota')], max_length=20)),
                ('status_persetujuan', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Setuju'), ('REJECTED', 'Tolak')], default='PENDING', max_length=20)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capstone_system.mahasiswa')),
                ('tim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anggota', to='capstone_system.tim')),
            ],
        ),
        migrations.AddField(
            model_name='proposalcapstone',
            name='tim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposal', to='capstone_system.tim'),
        ),
    ]
