# Generated by Django 5.2.8 on 2026-05-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_system', '0002_tim_remove_proposalcapstone_nim_anggota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tim',
            name='kategori',
            field=models.CharField(blank=True, choices=[('EPD', 'EPD'), ('SM', 'SM')], max_length=3, null=True),
        ),
    ]
