# Generated by Django 5.2.8 on 2026-05-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_system', '0003_tim_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='kategori',
            field=models.CharField(blank=True, choices=[('EPD', 'EPD'), ('SM', 'SM')], max_length=3, null=True),
        ),
    ]
