# Generated by Django 5.2.8 on 2026-05-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_system', '0004_mahasiswa_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='anggotatim',
            name='kategori',
            field=models.CharField(blank=True, choices=[('EPD', 'EPD'), ('SM', 'SM')], max_length=3, null=True),
        ),
    ]
