# Generated by Django 5.2.8 on 2026-06-01 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_system', '0005_anggotatim_kategori'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalcapstone',
            name='kategori',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='kategori',
        ),
    ]
