# Generated by Django 5.2.8 on 2026-06-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_system', '0006_remove_proposalcapstone_kategori_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalcapstone',
            name='catatan_cp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposalcapstone',
            name='catatan_pb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposalcapstone',
            name='status_cp',
            field=models.CharField(choices=[('BELUM_REVIEW', 'Belum Review'), ('SEDANG_REVIEW', 'Sedang Review'), ('DITERIMA', 'Diterima'), ('DITOLAK', 'Ditolak'), ('REVISI', 'Perlu Revisi')], default='BELUM_REVIEW', max_length=20),
        ),
        migrations.AddField(
            model_name='proposalcapstone',
            name='status_pb',
            field=models.CharField(choices=[('BELUM_REVIEW', 'Belum Review'), ('SEDANG_REVIEW', 'Sedang Review'), ('DITERIMA', 'Diterima'), ('DITOLAK', 'Ditolak'), ('REVISI', 'Perlu Revisi')], default='BELUM_REVIEW', max_length=20),
        ),
        migrations.AddField(
            model_name='proposalcapstone',
            name='tanggal_review_cp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposalcapstone',
            name='tanggal_review_pb',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposalcapstone',
            name='status',
            field=models.CharField(choices=[('BELUM_REVIEW', 'Belum Review'), ('SEDANG_REVIEW', 'Sedang Review'), ('DITERIMA', 'Diterima'), ('DITOLAK', 'Ditolak'), ('REVISI', 'Perlu Revisi')], default='BELUM_REVIEW', max_length=20),
        ),
    ]
