# Generated by Django 5.2.8 on 2026-06-09 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_system', '0007_proposalcapstone_catatan_cp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalcapstone',
            name='cp_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_review', to='capstone_system.dosencp'),
        ),
    ]
