# Generated by Django 5.2.8 on 2026-06-14 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_system', '0008_proposalcapstone_cp_reviewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalcapstone',
            name='keterangan',
        ),
        migrations.RemoveField(
            model_name='proposalcapstone',
            name='status',
        ),
    ]
