# Generated by Django 5.2.8 on 2026-06-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_system', '0009_remove_proposalcapstone_keterangan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwalkonsultasi',
            name='jumlah_dipesan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jadwalkonsultasi',
            name='kuota',
            field=models.IntegerField(default=3),
        ),
    ]
