# Generated by Django 5.2.8 on 2026-06-20 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_system', '0010_jadwalkonsultasi_jumlah_dipesan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingJadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_booking', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('CANCELLED', 'Cancelled'), ('DONE', 'Done')], default='BOOKED', max_length=20)),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capstone_system.jadwalkonsultasi')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capstone_system.mahasiswa')),
            ],
        ),
    ]
