# Generated by Django 5.2.8 on 2026-06-20 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_system', '0011_bookingjadwal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jadwalkonsultasi',
            name='status',
        ),
        migrations.AlterField(
            model_name='bookingjadwal',
            name='jadwal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='capstone_system.jadwalkonsultasi'),
        ),
        migrations.AlterField(
            model_name='bookingjadwal',
            name='mahasiswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_jadwal', to='capstone_system.mahasiswa'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingjadwal',
            unique_together={('mahasiswa', 'jadwal')},
        ),
    ]
