# Generated by Django 5.2.8 on 2026-06-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_system', '0012_remove_jadwalkonsultasi_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosen',
            name='asal_prodi',
            field=models.CharField(default='Teknik Informatika', max_length=100),
        ),
    ]
