# Generated by Django 5.2.8 on 2026-06-26 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_system', '0013_dosen_asal_prodi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dosen',
            old_name='asal_prodi',
            new_name='prodi',
        ),
    ]
