# Generated by Django 5.2.8 on 2026-06-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_system', '0014_rename_asal_prodi_dosen_prodi'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='status',
            field=models.CharField(choices=[('Aktif', 'Aktif'), ('Tidak Aktif', 'Tidak Aktif'), ('Arsip', 'Arsip')], default='AKTIF', max_length=20),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='tanggal_masuk',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='status_aktif',
            field=models.CharField(choices=[('AKTIF', 'Aktif'), ('NONAKTIF', 'Non Aktif'), ('PINDAH', 'Pindah Prodi')], default='AKTIF', max_length=20),
        ),
    ]
