# Generated by Django 5.2.8 on 2026-06-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_system', '0015_mahasiswa_status_mahasiswa_tanggal_masuk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='status',
            field=models.CharField(choices=[('AKTIF', 'Aktif'), ('NONAKTIF', 'Tidak Aktif'), ('ARSIP', 'Arsip')], default='AKTIF', max_length=20),
        ),
    ]
