# Generated by Django 5.2.8 on 2026-07-22 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_system', '0016_alter_mahasiswa_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatFeedbackProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.CharField(choices=[('PB', 'Dosen Pembimbing'), ('CP', 'Dosen Capstone Project')], max_length=2)),
                ('status', models.CharField(choices=[('BELUM_REVIEW', 'Belum Review'), ('SEDANG_REVIEW', 'Sedang Review'), ('DITERIMA', 'Diterima'), ('DITOLAK', 'Ditolak'), ('REVISI', 'Perlu Revisi')], max_length=20)),
                ('catatan', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dosen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='capstone_system.dosen')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_feedback', to='capstone_system.proposalcapstone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiwayatFeedbackResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('BELUM_REVIEW', 'Belum Review'), ('DISETUJUI', 'Disetujui'), ('DITOLAK', 'Ditolak'), ('REVISI', 'Revisi')], max_length=20)),
                ('catatan', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dosen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='capstone_system.dosen')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_feedback', to='capstone_system.resume')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
