# Generated by Django 5.2.8 on 2026-07-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_system', '0017_riwayatfeedbackproposal_riwayatfeedbackresume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosenpembimbing',
            name='batas_bimbingan',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='dosenpembimbing',
            name='jumlah_bimbingan_sekarang',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
