# Generated by Django 5.2.8 on 2026-07-25 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_system', '0018_alter_dosenpembimbing_batas_bimbingan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dosenpembimbing',
            name='jumlah_bimbingan_sekarang',
        ),
    ]
