# Generated by Django 5.2.8 on 2026-07-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_system', '0019_remove_dosenpembimbing_jumlah_bimbingan_sekarang'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
