# Generated by Django 5.2.8 on 2026-08-08 13:03

import capstone_system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_system', '0020_user_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalcapstone',
            name='file',
            field=models.FileField(upload_to='proposal/', validators=[capstone_system.models.validate_pdf_file]),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file_resume',
            field=models.FileField(upload_to='resume/', validators=[capstone_system.models.validate_pdf_file]),
        ),
    ]
