# Generated by Django 5.2.8 on 2026-08-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_system', '0021_alter_proposalcapstone_file_alter_resume_file_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MAHASISWA', 'Mahasiswa'), ('DOSENCP', 'Dosen CP'), ('DOSENPB', 'Dosen Pembimbing'), ('KAPRODI', 'Kaprodi')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='active_role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='capstone_system.role'),
        ),
    ]
