# Generated by Django 5.2.8 on 2026-08-22 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_system', '0022_role_user_active_role_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalcapstone',
            name='dosen_pertama',
            field=models.ForeignKey(blank=True, help_text='Dosen yang pertama kali memberi status di siklus ini', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_status_pertama', to='capstone_system.dosencp'),
        ),
        migrations.AddField(
            model_name='proposalcapstone',
            name='semua_catatan_cp',
            field=models.TextField(blank=True, help_text='JSON array dari semua catatan dosen CP', null=True),
        ),
        migrations.AddField(
            model_name='proposalcapstone',
            name='status_terkunci',
            field=models.CharField(blank=True, choices=[('BELUM_REVIEW', 'Belum Review'), ('SEDANG_REVIEW', 'Sedang Review'), ('DITERIMA', 'Diterima'), ('DITOLAK', 'Ditolak'), ('REVISI', 'Perlu Revisi')], help_text='Status yang sudah ditetapkan oleh dosen pertama (tidak bisa diubah)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='proposalcapstone',
            name='total_revisi',
            field=models.PositiveIntegerField(default=0, help_text='Total siklus revisi yang sudah dilakukan'),
        ),
    ]
