# Generated by Django 5.2.8 on 2026-08-22 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_system', '0023_proposalcapstone_dosen_pertama_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalcapstone',
            name='dosen_pertama',
        ),
        migrations.RemoveField(
            model_name='proposalcapstone',
            name='semua_catatan_cp',
        ),
        migrations.RemoveField(
            model_name='proposalcapstone',
            name='status_terkunci',
        ),
        migrations.RemoveField(
            model_name='proposalcapstone',
            name='total_revisi',
        ),
    ]
